version: '3'

services:
    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: safeguideuser
        POSTGRES_PASSWORD: password
        POSTGRES_DB: safeguide
      volumes:
          - ./data:/var/lib/postgresql/data
      ports:
          - "5432:5432"
      expose:
            - "5432"
    app:
      build: .
      volumes:
        - ./app:/app
      restart: always
      ports:
        - '4000:4000'
      environment:
        DATABASE_URL: ${DATABASE_URL_DOCKER}
      depends_on:
        - db
volumes:
  db:
