version: '3'

services:
    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: p6SuJ1A09RXzXoKg
        POSTGRES_DB: postgres
      volumes:
          - ./data:/var/lib/postgresql/data
      ports:
          - "5432:5432"
      expose:
            - "5432"
    app:
      build: .
      volumes:
        - ./app:/app
      restart: always
      ports:
        - '4000:4000'
      environment:
        DATABASE_URL: postgresql://postgres:p6SuJ1A09RXzXoKg@db.scmtwxdvsullwsfpzhcp.supabase.co:5432/postgres
      depends_on:
        - db
volumes:
  db:
