version: "3.9"

services:
    deno:
        container_name: deno
        image: deno
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PORT}:${PORT}"
    db:
        image: postgres
        restart: always
        environment:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydb
        volumes:
           - ./data:/var/lib/postgresql/data