version: "3.9"

services:
    deno:
        container_name: deno
        image: deno
        restart: always
        build:
            context: app
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PORT}:${PORT}"
    db:
        image: postgres
        restart: always
        environment:
          POSTGRES_USER: safeguideuser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: safeguide
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        expose:
            - "5432"
        