version: "3.9"
volumes:
  app-data:
    driver: local


services:
    db:
        image: postgres
        restart: always
        environment:
          POSTGRES_USER: safeguideuser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: safeguide
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        expose:
            - "5432"
    deno:
        container_name: deno
        image: deno
        restart: always
        volumes:
            - app-data:/app    
        depends_on:
            - db
        build:
            context: app
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PORT}:${PORT}"

        